S3 upload api
actris-cloudnet/dataportal pull request #42
Opened 2020-10-30 12:43 UTC by lakka

This PR:
- Adds a route for uploading files to S3
- Refractors routes to their own classes

2020-10-31 08:47 UTC, tukiains requested changes
Nyt on sopivan kokoinen pullari arvioitavaksi, kiitos! Routet refaktoroitu järkevästi omiin tiedostoihin ja itse S3-totetutus näyttää selkeältä, hyvää duunia. Jotain kummallisuuksia koodissa, enkä ole ihan varma kaikista nimeämisistä: katso kommentit.

2020-10-31 08:47 UTC, tukiains commented on backend/src/routes/upload.ts
> +      const md = await this.uploadedMetadataRepo.findOne({where: {hashSum, site: {id: site}}, relations: ['site']})
Toimisiko ihan vaan pelkkä  `findOne(hashSum)` ?

2020-10-31 08:47 UTC, tukiains commented on backend/src/routes/upload.ts
> +        console.error(err)
onko tarkoituksella jätetty?

2020-10-31 08:47 UTC, tukiains commented on backend/src/routes/upload.ts
> +      await this.uploadedMetadataRepo.update({hashSum}, {status: Status.UPLOADED, updatedAt: new Date() })
`{hashSum}` on siistimpi ilman sulkuja ja `updatedAt` päivitys on turha tässä, koska se on määritelty entityssä @BeforeUpdate kohdassa jo.

2020-10-31 08:47 UTC, tukiains commented on backend/tests/integration/sequential/upload.test.ts
> +import axios from 'axios'
Kattavat testit, hyvä!

2020-11-02 07:27 UTC, lakka commented on backend/src/entity/Upload.ts
> +  hashSum!: string
Koko hash tallennetaan. Huomaa, että API käyttää MD5-summaa SHA256:n sijasta. Tämä johtuu siitä, että S3 tukee MD5 hash-summalla verifiointia. Kentän nimen voin kyllä muuttaa, laitoin vain saman kuin aikaisemmassa apispecissä.

2020-11-02 07:31 UTC, lakka commented on backend/src/server.ts
> +import {FileController} from './routes/file'
Valitsin nimeksi controller, koska huomasin, että me itseasiassa noudatetaan aika tarkasti model-view-controller (MVC) -paradigmaa: https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller . Mutta voidaan käyttää myös Routesia.

2020-11-02 07:32 UTC, lakka commented on backend/src/routes/upload.ts
> +      const md = await this.uploadedMetadataRepo.findOne({where: {hashSum, site: {id: site}}, relations: ['site']})
Ei. Kyselyssä pitää määrittää myös site, koska muuten site X voi ylikirjoittaa siten Y dataa, jos tietää hashin. Voisin lisätä testin tälle.

2020-11-02 07:36 UTC, lakka commented on backend/src/routes/upload.ts
> +      await this.uploadedMetadataRepo.update({hashSum}, {status: Status.UPLOADED, updatedAt: new Date() })
`{hashSum}` on syntaktista karkkia ilmaisulle `{hashSum: hashSum}`. Tässä pitää määrittää kenttä, jonka perusteella etsitään (hashSum), koska hashSum ei ole taulun primary column. Huomaa, että metadatatietueilla on myös uuid:t. @BeforeUpdatea ei ajeta, kun kutsutaan `update`: https://github.com/typeorm/typeorm/issues/5385

2020-11-02 07:37 UTC, tukiains commented on backend/src/entity/Upload.ts
> +  hashSum!: string
Aah joo totta, se on MD5 nyt.

2020-11-02 07:38 UTC, tukiains commented on backend/src/server.ts
> +import {FileController} from './routes/file'
OK Controller on myös ihan perusteltu silloin. Voit päättää kumpaa tyyliä haluat käyttää.

2020-11-02 07:39 UTC, tukiains commented on backend/src/routes/upload.ts
> +      const md = await this.uploadedMetadataRepo.findOne({where: {hashSum, site: {id: site}}, relations: ['site']})
Joo testi olisi hyvä, ettei liian innokas refaktoroija vahingossa riko jotain.

2020-11-02 08:04 UTC, tukiains commented on backend/src/routes/upload.ts
> +      await this.uploadedMetadataRepo.update({hashSum}, {status: Status.UPLOADED, updatedAt: new Date() })
OK, huh, luulin, että nimen omaan ajetaan silloin, kun kutsutaan `update`. Voisit ehkä lisätä unit-testiin tarkastuksen tuolle `updatedAt` muutokselle ettei vahingossa riko sitä.

2020-11-02 08:06 UTC, lakka commented on backend/src/server.ts
> +  app.get('/api/files/:uuid', middleware.validateUuidParam, fileController.getFile)
Olen samaa mieltä, että näissä pitäisi olla sääntö. Refaktoroinnin yhdeydessä nimesin routeja uusiksi siten, että tuo metodi olisi aina nimen edessä, mikäli routelle on useampi metodi. Mikäli routelle ei voi tehdä mitään muuta kuin GETin, jätin etuliitteen pois. Voidaan myös sopia, että laitetaan etuliite myös näihin, jos se selkeyttää.

2020-11-02 08:07 UTC, lakka commented on backend/src/routes/upload.ts
> +  S3_BAD_HASH_ERROR_CODE, toArray,
Importit tulevat automaattisesti IDE:stä, joten en ala korjaamaan näitä käsin. Jos näihin halutaan joku tietty tyyli, niin ehkä sen voisi määritellä lintteriin?

2020-11-02 08:12 UTC, lakka commented on backend/src/routes/upload.ts
> +        if (uploadedMetadata == undefined) return next({ status: 404, errors: ['No metadata was found with provided id']})
Minusta on parempi olla eksplisiittinen, koska typeormin manuaalissa sanotaan, että funktio palauttaa nimenomaan `undefined`, jos haku ei tuota tulosta. En pitäisi mahdottomana, että tuo `Upload`-class evaluoituisi jossain (virhe) tilanteessa falseksi, ja siksi haluaisin olla tässä eksplisiittinen.

2020-11-02 08:14 UTC, tukiains commented on backend/src/routes/upload.ts
> +  S3_BAD_HASH_ERROR_CODE, toArray,
OK, ehkä ne voi olla miten sattuu tuolla ainakin toistaiseksi.

2020-11-02 08:15 UTC, lakka commented on backend/src/routes/upload.ts
> +      await this.uploadedMetadataRepo.update({hashSum}, {status: Status.UPLOADED, updatedAt: new Date() })
On jo

2020-11-02 08:18 UTC, tukiains commented on backend/src/routes/upload.ts
> +        if (uploadedMetadata == undefined) return next({ status: 404, errors: ['No metadata was found with provided id']})
Hyvä on sovitaan niin ja tehdään muut vastaavat (ainakin `findOne`, ehkä muitakin?) tarkastelut tällä tavalla myös.

2020-11-02 15:04 UTC, tukiains commented on backend/src/server.ts
> +  app.get('/api/files/:uuid', middleware.validateUuidParam, fileController.getFile)
Täytyy miettiä mikä toimisi parhaiten.

2020-11-02 15:04 UTC, tukiains approved these changes

2020-11-10 09:08 UTC, merged